### ISSUE TITLE
resolve / reject

### ISSUE THREAD

**Issue by azole** [luofungyi/nodejs-mfee16#3]
https://github.com/luofungyi/nodejs-mfee16/blob/95c8869cb4d282448fbf3c45d4a5c6058af4c43d/crawler/app2.js#L11

是故意把 reject 跟 resolve 用相反嗎？

你的程式執行後，在 下述程式中， data 會是什麼資料呢？

```javascript
fsPromise().then((data) => {
```

**Comment by luofungyi** [comment]
感謝指正。
